import 'package:flutter/cupertino.dart';
import 'package:flutter_weather_icons/flutter_weather_icons.dart';

var strings = {
  "en":{
    "dof":[
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday"
    ],
    "months":[
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December",
    ],
  },
  "ru":{
    "dof":[
      "Понедельник",
      "Вторник",
      "Среда",
      "Четверг",
      "Пятница",
      "Суббота",
      "Воскресенье"
    ],
    "months":[
      "Январь",
      "Февраль",
      "Март",
      "Апрель",
      "Май",
      "Июнь",
      "Июль",
      "Август",
      "Сентябрь",
      "Октябрь",
      "Ноябрь",
      "Декабрь",
    ]
  },
};

var icons = {
  "day":{
    200: WeatherIcons.wiDayThunderstorm,
    201: WeatherIcons.wiDayThunderstorm,
    201: WeatherIcons.wiDayThunderstorm,
    202: WeatherIcons.wiDayThunderstorm,
    210: WeatherIcons.wiDayThunderstorm,
    211: WeatherIcons.wiDayThunderstorm,
    212: WeatherIcons.wiDayThunderstorm,
    221: WeatherIcons.wiDayThunderstorm,
    230: WeatherIcons.wiDayThunderstorm,
    231: WeatherIcons.wiDayThunderstorm,
    232: WeatherIcons.wiDayThunderstorm,
    300: WeatherIcons.wiDayRainMix,
    301: WeatherIcons.wiDayRainMix,
    302: WeatherIcons.wiDayRainMix,
    310: WeatherIcons.wiDayRainMix,
    311: WeatherIcons.wiDayRainMix,
    312: WeatherIcons.wiDayRainMix,
    313: WeatherIcons.wiDayRainMix,
    314: WeatherIcons.wiDayRainMix,
    321: WeatherIcons.wiDayRainMix,
    500: WeatherIcons.wiDayRain,
    501: WeatherIcons.wiDayRain,
    502: WeatherIcons.wiDayRain,
    503: WeatherIcons.wiDayRain,
    504: WeatherIcons.wiDayRain,
    511: WeatherIcons.wiDayRain,
    520: WeatherIcons.wiDayRain,
    521: WeatherIcons.wiDayRain,
    522: WeatherIcons.wiDayRain,
    531: WeatherIcons.wiDayRain,
    600: WeatherIcons.wiDaySnow,
    601: WeatherIcons.wiDaySnow,
    602: WeatherIcons.wiDaySnow,
    611: WeatherIcons.wiDaySnow,
    612: WeatherIcons.wiDaySnow,
    613: WeatherIcons.wiDaySnow,
    615: WeatherIcons.wiDaySnow,
    616: WeatherIcons.wiDaySnow,
    620: WeatherIcons.wiDaySnow,
    621: WeatherIcons.wiDaySnow,
    622: WeatherIcons.wiDaySnow,
    701: WeatherIcons.wiFog,
    711: WeatherIcons.wiSmoke,
    721: WeatherIcons.wiDayHaze,
    731: WeatherIcons.wiSandstorm,
    741: WeatherIcons.wiFog,
    751: WeatherIcons.wiSandstorm,
    761: WeatherIcons.wiDust,
    762: WeatherIcons.wiVolcano,
    771: WeatherIcons.wiStrongWind,
    781: WeatherIcons.wiTornado,
    800: WeatherIcons.wiDaySunny,
    801: WeatherIcons.wiDayCloudy,
    802: WeatherIcons.wiDayCloudy,
    803: WeatherIcons.wiDayCloudy,
    804: WeatherIcons.wiDayCloudy,
  },
  "night":{
    200: WeatherIcons.wiNightThunderstorm,
    201: WeatherIcons.wiNightThunderstorm,
    201: WeatherIcons.wiNightThunderstorm,
    202: WeatherIcons.wiNightThunderstorm,
    210: WeatherIcons.wiNightThunderstorm,
    211: WeatherIcons.wiNightThunderstorm,
    212: WeatherIcons.wiNightThunderstorm,
    221: WeatherIcons.wiNightThunderstorm,
    230: WeatherIcons.wiNightThunderstorm,
    231: WeatherIcons.wiNightThunderstorm,
    232: WeatherIcons.wiNightThunderstorm,
    300: WeatherIcons.wiNightRainMix,
    301: WeatherIcons.wiNightRainMix,
    302: WeatherIcons.wiNightRainMix,
    310: WeatherIcons.wiNightRainMix,
    311: WeatherIcons.wiNightRainMix,
    312: WeatherIcons.wiNightRainMix,
    313: WeatherIcons.wiNightRainMix,
    314: WeatherIcons.wiNightRainMix,
    321: WeatherIcons.wiNightRainMix,
    500: WeatherIcons.wiNightRain,
    501: WeatherIcons.wiNightRain,
    502: WeatherIcons.wiNightRain,
    503: WeatherIcons.wiNightRain,
    504: WeatherIcons.wiNightRain,
    511: WeatherIcons.wiNightRain,
    520: WeatherIcons.wiNightRain,
    521: WeatherIcons.wiNightRain,
    522: WeatherIcons.wiNightRain,
    531: WeatherIcons.wiNightRain,
    600: WeatherIcons.wiNightSnow,
    601: WeatherIcons.wiNightSnow,
    602: WeatherIcons.wiNightSnow,
    611: WeatherIcons.wiNightSnow,
    612: WeatherIcons.wiNightSnow,
    613: WeatherIcons.wiNightSnow,
    615: WeatherIcons.wiNightSnow,
    616: WeatherIcons.wiNightSnow,
    620: WeatherIcons.wiNightSnow,
    621: WeatherIcons.wiNightSnow,
    622: WeatherIcons.wiNightSnow,
    701: WeatherIcons.wiFog,
    711: WeatherIcons.wiSmoke,
    721: WeatherIcons.wiDayHaze,
    731: WeatherIcons.wiSandstorm,
    741: WeatherIcons.wiFog,
    751: WeatherIcons.wiSandstorm,
    761: WeatherIcons.wiDust,
    762: WeatherIcons.wiVolcano,
    771: WeatherIcons.wiStrongWind,
    781: WeatherIcons.wiTornado,
    800: WeatherIcons.wiNightClear,
    801: WeatherIcons.wiNightCloudy,
    802: WeatherIcons.wiNightCloudy,
    803: WeatherIcons.wiNightCloudy,
    804: WeatherIcons.wiNightCloudy,
  },
};


var weather_cond = {
  "en":{
    "wind":"Wind",
    "hum":"Humidity",
    "pres":"Pressure"
  },
  "ru":{
    "wind":"Ветер",
    "hum":"Влажность",
    "pres":"Давление"
  }
};